### ISSUE TITLE
does not reliably connect

### ISSUE THREAD

**Issue by BrianRayJ** [Microsoft/Windows-appsample-remote-system-sessions#2]
I have set the game up on different host/client combinations for 2 - 3 machines about 20 times today with only 1 successfully maintained join and play.  All 3 machines are located within a few feet of each other and a few feet of my wifi router.  Still working on it, but have not figured out why I cannot establish and/or maintain a connection.

I love this sample app, btw.

**Comment by bmitchell287** [comment]
@BrianRayJ  - Brian thanks much for trying out the sample, appreciated. Just to confirm, all devices are Bluetooth enabled and the "Share across devices" feature is enabled in the settings menu (Shared experiences)?

**Comment by bmitchell287** [comment]
@BrianRayJ - Closing for now, please reopen if you would like to investigate further. Thanks.

**Comment by BrianRayJ** [comment]
Hi Brendan,

I’m very sorry I missed this.  Yes, all devices are Bluetooth enabled and the “Share across devices” feature is enabled.  Two PCs running latest Win10 Insider preview.

To troubleshoot, I did actually remove Bluetooth from the manifest and gained connection from another PC, but only momentarily.  I also found the previous version ( published 2016?) of QuizGame on GitHub.  It is not nearly as finished of a product as yours, but using WiFi only, it connects just fine before running into unrelated issues.

Brian

Brian R. Jones | IT | Director of Application Operations | w: 817.262.6570 | c: 817.929.9249

[cid:image001.png@01CFF2DE.8B9B5C70]

**Comment by bmitchell287** [comment]
Thanks Brian, okay looks like environmentally that all your devices and configured properly and using the right version of the OS. From your original post this would seem so given that you had at least one client able to discover/ join the session and play through.  Let us try to reproduce this on a couple other devices, and we'll get back to you.

The older Quiz Game/network helper sample that you mentioned was the predecessor to this project. It used a different networking backbone than the Remote System Sessions API used in this sample.

**Comment by bmitchell287** [comment]
@BrianRayJ Brian, still looking into this. We're able to discover/join a session with multiple devices in our environment, but having another group of people try. Waiting to hear back.

**Comment by BrianRayJ** [comment]
Thanks!

Brian R. Jones | IT | Director of Application Operations | w: 817.262.6570 | c: 817.929.9249

[cid:image001.png@01CFF2DE.8B9B5C70]

**Comment by bmitchell287** [comment]
@BrianRayJ - Hi Brian, so we had another team with different hardware check out the sample and they ran through multiple scenarios to test with the app. They were able to get multiple participants connecting and discovering/joining the proximal sessions. When we did our testing we also tried via the corporate network and with a private Wi-Fi router and were able to join the game and participate amongst each device. And I'm sure you environmentally have everything configured correctly. The only other frequent message relayed was again make sure that the feature "Share across devices" must be set to "On" and "Everyone nearby." It's odd that one of your devices can join/play while the other partiicpant can't.

Listen we'll keep looking into this and update you if we hear more. Again thanks for trying this out.

**Comment by BrianRayJ** [comment]
Hi Brendan,

I’m sorry for the tardy response.  I’ve been traveling and have not had a chance to look into it again.  But I want you to know I greatly appreciate your assistance.

Brian

BrianJones
IT | Director of Application Operations | w: 817.262.6570 | c: 817.929.9249
[1460504366729_LSCO_4BRAND_LOCKUP-Cropped-resized.gif]
